name: Compilar y Publicar Release

on:
  push:
    tags:
      - 'v*' # Se activará automáticamente cuando crees un tag que empiece con "v" (ej: v1.0.0)

jobs:
  build-and-release:
    runs-on: windows-latest
    
    # Damos permisos al robot para escribir en la sección de Releases
    permissions:
      contents: write

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar entorno .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compilar el Mod
        run: dotnet build --configuration Release

      - name: Preparar carpeta del ZIP
        run: |
          mkdir Empaquetado\plugins
          copy bin\Release\net46\ModExportadorPrecios.dll Empaquetado\plugins\
          copy README.md Empaquetado\
          copy README_en.md Empaquetado\
          Compress-Archive -Path Empaquetado\* -DestinationPath ModExportadorPrecios.zip

      - name: Subir a GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: ModExportadorPrecios.zip
          generate_release_notes: true

      - name: Subir a NexusMods
        uses: Nexus-Mods/upload-action@main
        with:
          api_key: ${{ secrets.NEXUSMODS_API_KEY }}
          game_domain: supermarkettogether
          mod_id: 207
          file_group_id: ${{ secrets.NEXUSMODS_GROUP_ID }}
          filename: ModExportadorPrecios.zip
          version: ${{ github.ref_name }} # Esto tomará automáticamente el nombre de tu versión (ej: v1.0.4)
          description: "Lanzamiento de la versión ${{ github.ref_name }}. Puedes ver las notas de parche completas y todas las novedades en la sección de Releases de nuestro GitHub oficial."
          file_category: main